# Archivo de configuración de Render Blueprint

services:
  # Servicio de Base de Datos PostgreSQL
  - type: pserv
    name: analyticore-db
    plan: free # Puedes usar un plan de pago si necesitas más rendimiento
    region: oregon # Elige la región que mejor se adapte a tus necesidades
    
  # Servicio de Submisión (Python)
  - type: web
    name: analyticore-python
    env: python
    region: oregon
    plan: free
    dockerCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    dockerContext: ./python-service
    ports:
      - port: 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: analyticore-db
          property: connectionString
      - key: JAVA_SERVICE_URL
        fromService:
          name: analyticore-java
          property: httpsUri

  # Servicio de Análisis (Java)
  - type: web
    name: analyticore-java
    env: java
    region: oregon
    plan: free
    dockerCommand: java -jar app.jar
    dockerContext: ./java-service
    ports:
      - port: 8080
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: analyticore-db
          property: connectionString

  # Frontend (React con Nginx)
  - type: web
    name: analyticore-frontend
    env: static
    region: oregon
    plan: free
    dockerContext: ./frontend
    dockerCommand: nginx -g "daemon off;"
    ports:
      - port: 8080
    envVars:
      - key: REACT_APP_API_BASE_URL
        fromService:
          name: analyticore-python
          property: httpsUri